# Generated by Django 4.0.5 on 2022-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='product',
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('UzCard', 'UzCard'), ('Humo', 'Humo'), ('PaymeGo', 'PaymeGo'), ('Naqd', 'Naqd'), ('Click', 'Click')], default='Naqd', max_length=10),
        ),
    ]
