# Generated by Django 4.0.5 on 2022-06-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_volume_product_alter_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categories'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('UzCard', 'UzCard'), ('Click', 'Click'), ('Naqd', 'Naqd'), ('Humo', 'Humo'), ('PaymeGo', 'PaymeGo')], default='Naqd', max_length=10),
        ),
    ]
