# Generated by Django 4.0.5 on 2022-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_volume_category_alter_sale_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(blank=True, choices=[('Naqd', 'Naqd'), ('UzCard', 'UzCard'), ('PaymeGo', 'PaymeGo'), ('Humo', 'Humo'), ('Click', 'Click')], max_length=10, null=True),
        ),
    ]
