# Generated by Django 4.0.5 on 2022-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='sold_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(blank=True, choices=[('Humo', 'Humo'), ('Click', 'Click'), ('UzCard', 'UzCard'), ('Naqd', 'Naqd'), ('PaymeGo', 'PaymeGo')], max_length=10, null=True),
        ),
    ]
